# project_name=pof.pm
version: "3.6"
services:
  app:
    image: "gicmadev/pof.pm"
    tmpfs:
      - /app/tmp
    networks:
      - traefik
      - default
    depends_on:
      - db
    env_file: ./.env
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host:pof.pm"

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - default
    volumes:
      - ./dbdata:/var/lib/mysql
    env_file: ./.env

networks:
  traefik:
    external: true
